name: consistency

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  consistency:
    uses: openads-project/openads-dev-environment/.github/workflows/consistency.yml@main
    secrets: inherit
